---
#sending file to outbound, then doing asserts for each module

#- name: generate uuid with shell

- set_fact: uuid="{{99999 | random | to_uuid}}"
- debug: var=uuid

#- set_fact: file_base = "{{ file | basename }}"
#- debug: var = file_base

- name: Copy file to outbound from-a2a dir
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "{{transport_from_a2a_path}}/{{ file| basename }}-{{ uuid }}.xml"

#report START ------
- set_fact: counter="{{counter| int +1 }}"
  register: counter
- debug: var=counter

- name: create report headers
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/mlr-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: "Test num.,Test file,transmissionId,MLR result"

- name: update test results
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/mlr-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: '{{counter}},{{file}},{{uuid}}'
#report END -------

- include: log_checker.yml
...
