---
#- include: set-up.yml
#- name: Stop transport
#  shell: docker stop transport-from-a2a

- name: Clean storage path
  become: true
#  become_user: peppol
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /peppol/data/storage/unknown/
    - /peppol/data/storage/9908_987987987/
    - /peppol/data/storage/9908_998877665/
    - /peppol/data/storage/9908_789789789/
    - /peppol/data/storage/987987987/

- include: file_list.yml

- name: stop inbound for test #3
  shell: docker stop inbound
- pause:
    seconds: 5
- include: test_3.yml
- name: start inbound after test #3 is done
  shell: docker start inbound

#+++++++++++++++++++++++++++++++
#      Final report check
#+++++++++++++++++++++++++++++++
- include: report_checker.yml

...
