---
- include: file_list.yml

- name: stop inbound for test #3
  shell: docker stop inbound
- pause:
    seconds: 5
- include: test_3.yml
- name: start inbound after test #3 is done
  shell: docker start inbound

#+++++++++++++++++++++++++++++++
#      Final report check
#+++++++++++++++++++++++++++++++
- include: report_checker.yml

...
