---
- name: Copy file to inbound
  command: docker exec inbound ./send-to-peppol.sh -f /tmp/git/test-materials/suite/ehf_2.0_bii4_no.xml
  register: inbound_output
- name: find transmissionId
  shell: echo "{{inbound_output.stdout_lines[-5:]}}" |grep -oh 'transmissionId.*'|awk '{print $2}'| awk  -F"'" '{print $1}'
  register: transmissionId
- set_fact: transmissionId="{{ transmissionId.stdout}}"
- debug: var=transmissionId
...
