---
- name: Copy file to outbound from-a2a dir
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "{{transport_from_a2a_path}}" 
    mode: 0775
- set_fact: file="{{file}}"
- debug: var=file

- name: find fileName
  shell: echo "{{file}}" | grep .xml |xargs -L 1 basename
  register: fileName
- set_fact: fileName="{{fileName.stdout}}"
- debug: var=fileName

- set_fact: counter="{{counter| int +1 }}"
  register: counter

- debug: var=counter

- name: update test results
  lineinfile:
    create: yes
    dest: "{{report_path}}/spike-test-outbound.txt"
    state: present
    line: 'Filename {{counter}}: {{file}}'


...
