---
- include: file_to_transport-from-a2a.yml
  vars: 
    file: "{{item}}"
  with_fileglob:
    - "{{test_data_path}}/validation_test_suite/valid/*"
    - "{{test_data_path}}/svefaktura_1.0/SBDH_wrapped_examples/Valid/*"
    - "{{test_data_path}}/EHF_2.0.7/Valid/*"
...
