---
- name: Copy file to outbound from-a2a dir
  become: yes
  copy:
    src: "{{file}}"
    dest: /var/lib/docker/volumes/peppol2.0/data/transport/from-a2a
- pause:
    minutes: 3
- name: find fileName
  shell: echo "{{file}}" | grep .xml |xargs -L 1 basename
  register: fileName
- set_fact: fileName="{{fileName.stdout}}"
- debug: var=fileName

...
