---
- name: Copy file to outbound from-a2a dir
  become: "{{sudo}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "{{transport_from_a2a_path}}"

- set_fact: file="{{file}}"
- debug: var=file

- name: find fileName
  shell: echo "{{file}}" | grep .xml |xargs -L 1 basename
  register: fileName
- set_fact: fileName="{{fileName.stdout}}"
- debug: var=fileName

- set_fact: counter="{{counter| int +1 }}"
  register: counter
- debug: var=counter

- name: update test results
  lineinfile:
    create: yes
    dest: "{{report_path}}/outbound-valid-tests{{ansible_date_time.iso8601_basic}}.txt"
    state: present
    line: '{{counter}}|{{file}}'

- pause:
    seconds: 130

- include: log_checker.yml
...
