---
- include: transport_assert.yml
- include: assert.yml
  vars:
    module_name: preprocessing
  tags: preprocessing
- include: assert.yml
  vars:
    module_name: internal-routing
  tags: internal-routing
- include: assert.yml
  vars:
    module_name: validator
  tags: validator
- include: assert.yml
  vars:
    module_name: outbound
  tags: outbound
...
