---
- name: Show outbound log, search for fileName "{{ fileName }}"
  shell: docker logs outbound
  register: log

- name: fileName "{{ fileName }}" is found in outbound log 
  ignore_errors: yes
  assert:
    that:
      - "fileName in log.stdout"
    msg: "Failed"
  register: result

- set_fact: outbound_result="outbound={{result.msg}}"
- debug: var=outbound_result

- name: check if outbound sending has failed
  fail: msg="outbound test failed"
  when:
    - log.stdout | search(fileName+".*failed .* error")

...
