---

- name: get outbound log & check if uuid "{{ uuid }}" for "{{ file }}" is found
  ignore_errors: yes
  shell: docker service logs peppol_outbound | grep "{{ uuid }}"
#  shell: docker logs outbound | grep "{{ uuid }}"
  register: log
  until: uuid in log.stdout
  retries: 120
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- set_fact: outbound_result="Failed"
  when: log.rc != 0
- set_fact: outbound_result="All assertions passed"
  when: log.rc == 0
- debug: var=outbound_result

#check for successful sending and adjust report accordingly->
- name: Check if sending was OK for uuid "{{ uuid }}" "{{ file }}"
  set_fact: outbound_result="All assertions passed"
  when:
    - log.stdout | search(".*Message.*"+uuid+".*sent with")

- debug: var=outbound_result
...
