---
- name: Show outbound log, search for fileName "{{ fileName }}"
  shell: docker logs outbound
  register: log

- name: fileName "{{ fileName }}" is found in outbound log 
  ignore_errors: yes
  assert:
    that:
      - log.stdout | search(".*Message.*"+fileName+".*sent with")
    msg: "Failed"
  register: result

- set_fact: outbound_result="outbound={{result.msg}}"
#- debug: var=outbound_result

#check for failures as well and adjust report accordingly->
- name: check if outbound sending has failed
  set_fact: outbound_result="outbound=Failed"
  when:
    - log.stdout | search(".*Message processing failed.*"+fileName)

...
