---
- name: get preprocessing log & check if uuid "{{ uuid }}" "{{ file }}" is found
  shell: docker logs preprocessing
  register: log
  until: uuid in log.stdout
  retries: 60
  delay: 1

- name: Assert if uuid "{{ uuid }}" "{{ file }}" is found in preprocessing log 
  ignore_errors: yes
  assert:
    that:
      - "uuid in log.stdout"
    msg: "Failed"
  register: result

- set_fact: preprocessing_result="Preprocessing={{result.msg}}"
- debug: var=preprocessing_result
...
