---
- name: Show preprocessing log, search for uuid "{{ uuid }}" "{{ file }}"
  shell: docker logs preprocessing
  register: log

- name: Assert if uuid "{{ uuid }}" "{{ file }}" is found in preprocessing log 
  ignore_errors: yes
  assert:
    that:
      - "uuid in log.stdout"
    msg: "Failed"
  register: result

- set_fact: preprocessing_result="Preprocessing={{result.msg}}"
- debug: var=preprocessing_result
...
