---
#transport_assert.yml should search for transmissionid in A2A transport logs, fail if not found. 
- name: get transport-from-a2a log & check if uuid "{{ uuid }}" "{{ file }}" is found
  shell: docker logs transport-from-a2a | grep "{{ uuid }}"
  register: a2aLog
  until: uuid in a2aLog.stdout
  retries: 130
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- name:  uuid "{{ uuid }}" for "{{ file }}" is found in transports logs
  ignore_errors: yes
  assert:
    that:
      - a2aLog.rc==0
    msg: "Failed"
  register: result

- set_fact: transport_result="transport={{result.msg}}"
- debug: var=transport_result
...

