---
#transport_assert.yml should search for transmissionid in A2A and XIB logs, fail if not found in one of them. 

- name: Show A2A log
  shell: docker logs transport-from-a2a
  register: a2aLog
- name: Show XIB log
  shell: docker logs transport-from-xib
  register: xibLog

- name: fileName '{{ fileName }}' is found in transports logs
  ignore_errors: yes
  assert:
    that:
      - ("fileName in a2aLog.stdout") or ("fileName in xibLog.stdout")
    msg: "Failed"
  register: result

- set_fact: transport_result="transport={{result.msg}}"
- debug: var=transport_result

...

