---
- name: Show log, search for transmissionidi
  shell: docker logs {{module_name}}
  register: log

- name: transmissionid is found in {{module_name}} log 
  assert:
    that:
      - "transmissionId in log.stdout"
    msg: "tranmissionId should be found in '{{module_name}}' for file '{{ file }}'"
...
