---
#File_list.yml#
#This is where all the test materials are taken from #

- include: send_to_inbound_multiple_files.yml
  vars:
    file: "{{item}}"
  with_fileglob:
    - "{{test_data_path}}/files/validation_test_suite/valid/*"
    - "{{test_data_path}}/svefaktura_1.0/SBDH_wrapped_examples/Valid/*"
    - "{{test_data_path}}/EHF_2.0.7/Valid/*"
...

