---
#change search so that "tail" is used for getting script output, then grep in that result

- name: Copy file "{{file}}" to inbound
  shell: docker run -i --network peppol_back -v /test-materials:/test-materials -v /peppol:/peppol d-l-tools.ocnet.local:443/peppol2.0/inbound:latest ./send-to-peppol.sh -f "{{ file }}" -u http://inbound:8080/peppol-ap-inbound/as2
#inbound to swarm makes this obsolite->  shell: docker exec inbound ./send-to-peppol.sh -f "{{file}}"
  register: inbound_output
- set_fact: file="{{file}}"
- name: file that was sent to inbound
  debug: var=file

- pause:
    seconds: 5

- name: find transmissionId for "{{file}}"
  shell: echo "{{inbound_output.stdout_lines[-5:]}}" |grep -oh 'transmissionId.*'|awk '{print $2}'| awk  -F"'" '{print $1}'
  register: transmissionId
- set_fact: transmissionId="{{ transmissionId.stdout}}"
- name: find file in inbound log
  debug: var=transmissionId

#report START ------:
- set_fact: counter="{{counter| int +1 }}"
  register: counter

- debug: var=counter

- name: create report headers
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/inbound-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: "Test num.,Test file,transmissionId,preprocessing result,internal-routing result,validator result,transport result"

- name: update test results
  delegate_to: localhost
  lineinfile:
    create: no
    dest: "{{report_path}}/inbound-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: "{{counter}},{{file}},{{transmissionId}}"
#report END -------
...
