---
- name: Show log, search for transmissionID "{{ transmissionId }}"
  shell: docker logs internal-routing
  register: log

- name: transmissionID "{{ transmissionId }}" is found in internal-routing log 
  ignore_errors: yes
  assert:
    that:
      - "transmissionId in log.stdout"
    msg: "Failed"
  register: result

- set_fact: internal_routing_result="internal-routing={{result.msg}}"
- debug: var=internal_routing_result
...
