---
- name: get preprocessing log & check if transmissionId "{{ transmissionId }}" "{{ file }}" is found
  ignore_errors: yes
  become: "{{sudo}}"
  become_user: "{{user}}"
  shell: grep "{{ transmissionId }}" /peppol/logs/preprocessing/*.log
  register: log
  until: transmissionId in log.stdout
  retries: 200
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- set_fact: preprocessing_result="Failed"
  when: log.rc != 0
- set_fact: preprocessing_result="All assertions passed"
  when: log.rc == 0
- debug: var=preprocessing_result
...
