---
#sending file to inbound, then doing asserts for each module

- include: file_to_inbound.yml
- pause:
    seconds: 10

- include: preprocessing_assert.yml
- include: internal-routing_assert.yml
- include: validator_assert.yml
- include: transport_assert.yml

#report update START ---------------------
- name: update test results
  delegate_to: localhost
  lineinfile:
    create: no
    dest: "{{report_path}}/inbound-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    regexp: "^{{counter}},{{file}},{{transmissionId}}"
    line: "{{counter}},{{file}},{{transmissionId}},{{inbound_result}},{{preprocessing_result}},{{internal_routing_result}},{{validator_result}},{{transport_result}}"
#report update END -----------------------

- debug: 
    var: report_path
- name: register report
  delegate_to: localhost
  shell: cat "{{report_path}}/inbound-report-{{ansible_date_time.iso8601_basic}}.csv"
  register: report

- debug: 
    var: report

- name: check if any assert has failed up until now
  fail: msg="system test failed"
  when: 
    - "'Failed' in report.stdout"

...
