---
#sending file to inbound, then doing asserts for each module

- include: file_to_inbound.yml
- pause:
    seconds: 10

- include: assert.yml
  vars: 
    module_name: preprocessing
- include: assert.yml
  vars:
    module_name: internal-routing
- include: assert.yml
  vars:
    module_name: validator
- include: transport_assert.yml
...
