---
#sending file to inbound, then doing asserts for each module

- include: file_to_inbound.yml
- pause:
    seconds: 20

- include: preprocessing_assert.yml

#report update START ---------------------
- name: update test results
  lineinfile:
    create: yes
    dest: "{{report_path}}/inbound-report.txt"
    state: present
    regexp: "^Filename {{counter}}: {{file}} {{transmissionId}}"
    line: "Filename {{counter}}: {{file}} {{transmissionId}} here was assert"
#    line: "Filename {{counter}}: {{file}} {{transmissionId}} {{preprocessing_result}}"
#report update END -----------------------

#- include: assert.yml
#  vars:
#    module_name: internal-routing
#- include: assert.yml
#  vars:
#    module_name: validator
#- include: transport_assert.yml
...
