---
#sending file to inbound, then doing asserts for each module

- include: file_to_inbound.yml
- pause:
    seconds: 3

- include: preprocessing_assert.yml
- include: internal-routing_assert.yml
- include: validator_assert.yml
- include: transport_assert.yml

#report update START ---------------------
- name: update test results
  lineinfile:
    create: no
    dest: "{{report_path}}/inbound-report.txt"
    state: present
    regexp: "^{{counter}}|{{file}}|{{transmissionId}}"
    line: "{{counter}}|{{file}}|{{transmissionId}}|{{preprocessing_result}}|{{internal_routing_result}}|{{validator_result}}|{{transport_result}}"
#report update END -----------------------
...
