---
#File_list.yml#
#This is where all the test materials are taken from #

- include: send_to_inbound_multiple_files.yml
  vars: 
    file: "{{item}}"
  with_items:
    - templates/EHF_profile-bii05_invoice_OC.xml
    - templates/EHF_profile-bii05_invoice.xml
    - templates/EHF_profile-bii05_creditnote.xml
    - templates/EHF_profile-bii05_invoice.xml
    - templates/peppol-bis.xml
    - templates/SFTI_svefaktura_BasicInvoice-1.0_Invoice.xml
    - templates/EHF_catalogue_document_type_test.xml
    - templates/EHF_profile-bii05_invoice_OC_zero_values.xml
    - templates/EHF_peppol-bis-5a_invoice.xml
    - templates/peppol-bis-svefaktura2.xml
    - templates/EHF_profile-bii05_invoice-SBDH-senderID-different-EndPointId.xml
    - templates/SFTI_svefaktura_BasicInvoice-1.0_Invoice-SBDH-senderID-different-SellerParty.xml
    - templates/EHF-order-sample.xml
    - templates/EHF-order-response.xml
    - templates/SI-UBL-Netherlands-profile-bii04_invoice-ver1.1.xml
    - templates/SI-UBL-Netherlands-profile-bii04_invoice-ver1.1.x.xml
    - templates/SI-UBL-Netherlands-profile-bii04_invoice-ver1.2.xml
    - templates/EHF_profile-bii05_invoice_OC_zero_val_has_attachment_new_line.xml
    - templates/EHF_profile-bii05_invoice_invalid_4char_attachment.xml
    - templates/EHF_profile-bii05_invoice_OC_zero_val_has_attachment.xml
    - templates/EHF_profile-bii05_invoice_OC_zero_val_has_attachment_new_line_padding.xml
    - templates/svefaktura_1_BasicInvoice_ObjectEnvelope_double_SBDH.XML
    - templates/svekatalog_small.xml
    - templates/bis_DespatchAdvice_peppol30a_ver1_DESADV.xml
    - templates/EHF_profile-bii05_invoice_with_custom_namespace.xml
    - templates/peppol-bisv3.xml
    - templates/sveorder.xml
    - templates/BIS63A-invoice-response.xml
...
