---
#transport_assert.yml should search for transmissionid in A2A and XIB logs, fail if not found in one of them. 

- name: Show A2A log
  shell: docker logs transport-to-a2a
  register: a2aLog
- name: Show XIB log
  shell: docker logs transport-to-xib
  register: xibLog

- name: transmissionID '{{ transmissionId }}' is found in transports logs
  assert:
    that:
      - ("transmissionId in a2aLog.stdout") or ("transmissionId in xibLog.stdout")
    msg: "tranmissionId '{{ transmissionId }}' should be found in transports logs for file '{{ file }}'"
...

