---
- name: get validator log & check if transmissionId "{{ transmissionId }}" "{{ file }}" is found in validator
  become: "{{sudo}}"
  become_user: "{{user}}"
  ignore_errors: yes
  shell: grep "{{ transmissionId }}" /peppol/logs/validator/*.log
#  shell: docker logs validator | grep "{{ transmissionId }}"
  register: log
  until: transmissionId in log.stdout
  retries: 500
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- set_fact: validator_result="Failed"
  when: log.rc != 0
- set_fact: validator_result="All assertions passed"
  when: log.rc == 0
- debug: var=validator_result
...
