info:
  component: Peppol Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          basedir: ${user.home}/checkout
          uri: http://nocontrol.itella.net/gitbucket/Peppol/peppol2.0-configuration

security:
  basic:
    enable: false

server:
  port: 8888
management:
  context_path: /admin