#info:
#  component: Peppol Config Server
#spring:
#  application:
#    name: configserver
#    profiles:
#      active: native
#  jmx:
#    default_domain: cloud.config.server
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///K://configs


#security:
#  basic:
#    enabled: false

#server:
#  port: 8888
#management:
#  context_path: /admin

#  logging:
#      level:
#          org.springframework.cloud: 'DEBUG'

#info:
#  component: Peppol Config Server
#spring:
#  application:
#    name: configserver
#  jmx:
#    default_domain: cloud.config.server
#  cloud:
#    config:
#      server:
#        git:
#          basedir: /var/local/services/peppol2.0/configuration-server/checkout
#          uri: http://10.164.1.141/gitbucket/git/Peppol/peppol2.0-configuration.git
#
#security:
#  basic:
#    enabled: false
#
#server:
#  port: 8888
#management:
#  context_path: /admin
#
#  logging:
#      level:
#          org.springframework.cloud: 'DEBUG'