tests:
   support-ui:
     type: link
     params:
       reference: http://peppol.itella.net/login
   validation:
     type: link
     params:
       reference: http://validator:8083/
   configuration-server:
     type: reference
     params:
       reference: http://localhost:440/admin/health
   queue:
     type: queue
     params:
       exchange: peppol
       queue: events-persistence email-notificator persistence-test routing transport-in transport-out
       host: localhost
       port: 5672
       username: guest
       password: guest
       virtual host: /
   dataBase:
     type: DB-connection
     params:
       host: t-l-mysql01.ocnet.local
       port: 3306
       username: oxalis
       password: grAm0f0n_1982-X_
       DB-name: oxalis
       driver: mysql
   MQ-connection:
     type: MQ-connection
     params:
       host: s-l-web1.ocnet.local
       port: 5672
       username: guest
       password: guest
       virtual-host: /
   File-System-connection:
     type: File-System-connection
     params:
       readable-directory: C:\test_dir C:\test_dir
       writable-directory: C:\test_dir C:\test_dir
   module-configuration:
     type: module-configuration
     params:
       host: http://localhost:441
       module-names: events-persistence transport
       profile: development
