---
- name: get email-notificator log & check if transmissionId "{{ transmissionId }}" "{{ file }}" is found
  ignore_errors: yes
  shell: docker logs email-notificator | grep "{{ transmissionId }}"
  register: log
  until: transmissionId in log.stdout
  retries: 60
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- set_fact: email_notificator_result="Failed"
  when: log.rc != 0
- set_fact: email_notificator_result="All assertions passed"
  when: log.rc == 0
- debug: var=email_notificator_result
...
