---
- name: get email-notificator log & check if transmissionId "{{ transmissionId }}" "{{ file }}" is found
  shell: docker logs email-notificator
  register: log
  until: transmissionId in log.stdout
  retries: 60
  delay: 1

- name: Assert if transmissionID "{{ transmissionId }}" "{{ file }}" is found in email-notificator log 
  ignore_errors: yes
  assert:
    that:
      - "transmissionId in log.stdout"
    msg: "Failed"
  register: result

- set_fact: email_notificator_result="email-notificator={{result.msg}}"
- debug: var=email_notificator_result
...
