---
- name: Copy file to inbound
  shell: docker run -i --network peppol_back -v /test-materials:/test-materials -v /peppol:/peppol d-l-tools.ocnet.local:443/peppol2.0/inbound:latest ./send-to-peppol.sh -f "{{ file }}" -u http://inbound:8080/peppol-ap-inbound/as2
#inbound to swarm makes this obsolite->  shell: docker exec inbound ./send-to-peppol.sh -f "{{file}}"
  register: inbound_output
- set_fact: file="{{file}}"
- debug: var=file
- pause:
    seconds: 5
- name: find transmissionId
  shell: echo "{{inbound_output.stdout_lines[-5:]}}" |grep -oh 'transmissionId.*'|awk '{print $2}'| awk  -F"'" '{print $1}'
  register: transmissionId

- set_fact: transmissionId="{{ transmissionId.stdout}}"
- debug: var=transmissionId

- name: ensure that transmissionId is not empty
  ignore_errors: yes
  assert:
    that:
      - transmissionId is defined and transmissionId != ""
    msg: "Failed- transmissionId was not found in Inbound"
  when: file != "/test-materials/validation_test_suite/invalid/image_example.jpg.xml"
  register: transmissionIdIsEmpty

- name: test case when inbound rejects invalid message and transmissionId is not set
  set_fact: inbound_result="Inbound rejected message"
  when: file == "/test-materials/validation_test_suite/invalid/image_example.jpg.xml"

- set_fact: inbound_result="{{transmissionIdIsEmpty.msg}}"
  when: transmissionIdIsEmpty.msg is defined
- debug: var=inbound_result

#report START ------:
- set_fact: counter="{{counter| int +1 }}"
  register: counter

- debug: var=counter

- name: create report headers
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/inbound-invalid-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: "Test num.,Test file,transmissionId,inbound result,preprocessing result,internal-routing result,validator result,email-notificator result"

- name: update test results
  delegate_to: localhost
  lineinfile:
    create: no
    dest: "{{report_path}}/inbound-invalid-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: "{{counter}},{{file}},{{transmissionId}},{{inbound_result}}"
#report END -------
...
