---
#- include: set-up.yml

- include: file_to_inbound.yml
  tags: 
    - inbound
    - file_to_inbound
    - preprocessing
- include: assert.yml
  vars: 
    module_name: preprocessing
  tags: preprocessing
- include: assert.yml
  vars:
    module_name: internal-routing
  tags: internal-routing
- pause:
    seconds: 10
- include: validator_assert.yml
- include: assert.yml
  vars:
    module_name: email-notificator

...
