---
- name: get validator log & check if transmissionId "{{ transmissionId }}" "{{ file }}" is found
  ignore_errors: yes
  shell: docker logs validator
  register: log
  until: transmissionId in log.stdout
  retries: 60
  delay: 1

- name: Assert if transmissionID "{{ transmissionId }}" "{{ file }}" is found in validator log 
  ignore_errors: yes
  assert:
    that:
      - "transmissionId in log.stdout"
    msg: "Failed"
  register: result

- set_fact: validator_result="validator={{result.msg}}"
- debug: var=validator_result
...
