#spring:
#  application:
#    name: 'zuul-proxy'
#
#server:
#  port: ${PORT:8989}
#zuul:
#  routes:
#    validator: /validator/**
#
#peppol:
#  zuul:
#    proxy:
#      allowFrom: '*'
#      denyFrom: 192.168.1.200
#      servicesAllowFrom:
#        validator: 192.168.1.110
#      servicesDenyFrom:
#        validator: 192.168.1.200
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

spring:
  http:
    multipart:
      max-file-size: 101Mb # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      max-request-size: 1024Mb # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.

multipart:
      max-file-size: 101Mb # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
      max-request-size: 1024Mb # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.