spring:
  application:
    name: 'zuul-proxy'

server:
  port: ${PORT:8989}
zuul:
  routes:
    validator: /validator/**

peppol:
  zuul:
    proxy:
      allowFrom: '*'
#      denyFrom: 192.168.1.200
#      servicesAllowFrom:
#        validator: 192.168.1.110
#      servicesDenyFrom:
#        validator: 192.168.1.200

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000