---
- name: Clean storage path
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /peppol/data/storage/unknown/
    - /peppol/data/storage/9908_987987987/
    - /peppol/data/storage/9908_998877665/
    - /peppol/data/storage/9908_789789789/
    - /peppol/data/storage/987987987/
...
