---
- name: Show email-notificator log, search for uuid "{{ uuid }}" "{{ file }}"
  shell: docker logs email-notificator
  register: log

- name: Assert if uuid "{{ uuid }}" "{{ file }}" is found in email-notificator log 
  ignore_errors: yes
  assert:
    that:
      - "uuid in log.stdout"
    msg: "Failed"
  register: result

- set_fact: email_notificator_result="email-notificator={{result.msg}}"
- debug: var=email_notificator_result
...
