---
#file_list.yml#
#This is where all the test materials are taken from #

- include: file_to_transport-from-a2a.yml
  vars: 
    file: "{{item}}"
  with_items:
    - "{{test_data_path}}/validation_test_suite/invalid/EHF_profile-bii05_invoice_invalid.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/Svefaktura2_profile-bii05_invoice.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/EHF_profile-bii05_invoice_invalid_2.0.9.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/EHF_profile-bii05_invoice_OC_zero_values_structural-error.xml" 
    - "{{test_data_path}}/validation_test_suite/invalid/empty.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/image_example.jpg.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/peppol-bis-04-32307653-invalid-ProfileID.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/random.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/EHF_profile-bii05_creditnote-no-SBDH.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/EHF_profile-biixy-ver2.0-invoice.xml"
    - "{{test_data_path}}/validation_test_suite/invalid/unrecognized_document_type.xml"
...
