---
- name: Show log, search for uuid "{{ uuid }}"
  shell: docker logs internal-routing
  register: log

- name: uuid "{{ uuid }}" is found in internal-routing log 
  ignore_errors: yes
  assert:
    that:
      - "uuid in log.stdout"
    msg: "Failed"
  register: result

- set_fact: internal_routing_result="internal-routing={{result.msg}}"
- debug: var=internal_routing_result
...
