---
- name: get internal-routing log & check if uuid "{{ uuid }}" "{{ file }}" is found in internal-routing
  ignore_errors: yes
  shell: docker logs internal-routing
  register: log
  until: "uuid in log.stdout"
  retries: 60
  delay: 1

- name: uuid "{{ uuid }}" "{{ file }}" is found in internal-routing log 
  ignore_errors: yes
  assert:
    that:
      - "uuid in log.stdout"
    msg: "Failed"
  register: result

- set_fact: internal_routing_result="internal-routing={{result.msg}}"
- debug: var=internal_routing_result
...
