---
#transport_assert.yml should search for transmissionid in A2A log, fail if not found. 

- name: get transport-from-a2a log & check if uuid "{{ uuid }}" "{{ file }}" is found in transport-from-a2a
  ignore_errors: yes
  shell: docker logs transport-from-a2a | grep "{{ uuid }}"
  register: a2aLog
  until: uuid in a2aLog.stdout
  retries: 130
  delay: 1

#rc is response code for shell commands 0=success and anything else=failed
- name: uuid '{{ uuid }}' "{{ file }}" is found in transport log
  ignore_errors: yes
  assert:
    that:
      - a2aLog.rc is defined and a2aLog.rc==0
    msg: "Failed- uuid not found"
  register: result

- set_fact: transport_result="{{result.msg}}"
- debug: var=transport_result
...

