#complete configuration for stage
configurations:
    databases:
        db1: jdbc:mysql://mysql:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: rabbitmq
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: /etc/resources/validation-result
tests:
   events-persistence:
        producers:
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/ehf.xml
                db connection: db1
                endpoint: events-persistence-integration-test
                DB preprocess querry: delete from messages where invoice_number='20828'
        subscribers:
            - db subscriber:
                db connection: db1
                timeout: 5000
                query: select count(*) from messages where invoice_number="20828"
                consumers: 4
        consumers:
            - DB test:
                id: 4
                name: Message persisted into DB positive test
                connection string: db1
                expected value: 1
   eventing:
        producers:
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source: integration-test-a2a
                source directory: /etc/resources/events-persistence-test/ehf.xml
                db connection: db1
                endpoint: integration-test-endpoint
                endpoint type: outbound
                DB preprocess querry: delete from messages where invoice_number='20828'
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source: integration-test-xib
                source directory: /etc/resources/events-persistence-test/rejected.xml
                db connection: db1
                endpoint: integration-test-endpoint
                endpoint type: outbound
                DB preprocess querry: delete from messages where invoice_number='61016660'
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                endpoint type: outbound
                source: integration-test-xib
                source directory: /etc/resources/events-persistence-test/invalid.xml
                endpoint: integration-test-endpoint
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                endpoint type: outbound
                source: integration-test-xib
                source directory: /etc/resources/events-persistence-test/invalid-snc-test.xml
                endpoint: integration-test-endpoint
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source: integration-test-xib
                source directory: /etc/resources/events-persistence-test/logger_xib_test.xml
                endpoint type: outbound
                endpoint: integration-test-endpoint
        subscribers:
            - snc subscriber:
                source directory: /peppol/data/snc-stub
                consumers: 5
            - directory subscriber:
                consumers: 6
                source directory: /peppol/data/eventing/a2a/mlr
            - directory subscriber:
                consumers: 7 9
                source directory: /peppol/data/eventing/xib/mlr
            - directory subscriber:
                consumers: 8
                source directory: /peppol/data/eventing/xib/wwd
        consumers:
            - file test:
                name: MLR a2a accepted creation test
                id: 6
                expected value: ehf-ap-mlr.xml
                timeout: 16000
            - file test:
                name: MLR xib rejected creation test
                id: 7
                expected value: rejected-re-mlr.xml
                timeout: 16000
            - wwd test:
                name: Web Watch Dog successful report test
                id: 8
                expected value: SEMAIDPOST_PEPPOL_XIB_status_logger_xib_test
                timeout: 16000
            - mlr test:
                name: IO exception in mlr test
                id: 9
                expected value: invalid-er-mlr.xml
                timeout: 16000
            - snc test:
                name: SNC ticket creation test
                id: 5
                expected value: 9908:937270062
                timeout: 16000
   support-ui:
        producers:
            - file producer:
                source directory: /etc/resources/support-ui-test/d78a50b0-eafa-41e2-b5ed-3f74989b1ced.xml
                destination directory: /peppol/data/storage/support-ui-test.xml
        subscribers:
            - file subscriber:
                consumers: 11
                timeout: 500
                source file: /peppol/data/storage/support-ui-test.xml
        consumers:
            - file download test:
                id: 11
                name: support ui download test
                action: download
                link: http://support-ui:8080/rest/outbound/download/
                expected value: true
   validation:
        producers:
            - file producer:
                source directory: /etc/resources/validation-xml-test
                destination directory: /peppol/data/storage/integration-test
            - mq producer:
                mq connection: mq1
                source directory: /peppol/data/storage/integration-test
                destination queue: validator
                endpoint: validation-integration-test
            - web ui producer:
                source directory: /etc/resources/validation-xml-test
                destination link: http://validator:8080/validator/
                result directory: validation result folder
            - rest producer:
                source directory: /etc/resources/validation-xml-test
                destination link: http://validator:8080/validator/validate
                result directory: validation result folder
                rest method: post
        subscribers:
            - mq subscriber:
                source queue: validation-integration-test
                timeout: 1500
                consumers: 1
            - snc subscriber:
                consumers: 2
                timeout: 500
            - file subscriber:
                source file:  /etc/resources/validation-result/restResult
                consumers: 3
            - file subscriber:
                source file:  /etc/resources/validation-result/webUiResult
                consumers: 2
        consumers:
            - queue msg count check:
                id: 1
                expected value: 4
                name: validation Mq check
            - web ui check:
                id: 2
                expected value: 4
                name: validation web ui check
            - rest check:
                id: 3
                expected value: 4
                name: validation rest check
