configurations:
    databases:
        db1: jdbc:mysql://mysql:3306/oxalis?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: 10.117.83.136
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result
tests:
   validation:
     producers:
      file producer:
        source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-xml-test
        destination directory: C:\Peppol\tmp\tmp\integration-test
      mq producer:
         mq connection: mq1
         source directory: C:\Peppol\tmp\tmp\integration-test
         destination queue: validator
         endpoint: validation-integration-test
      # rest producer:
       #  source directory: /etc/resources/validation-xml-test
        # destination link: http://validator:8080/validator/validate
         #result directory: validation result folder
#         rest method: post
     subscribers:
        - mq subscriber:
            source queue: validation-integration-test
            timeout: 1500
            consumers: 1
      #  - file subscriber:
       #     source file:  C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result\restResult
        #    consumers: 3
       # - file subscriber:
        #    source file:  C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result\webUiResult
         #   consumers: 2
     consumers:
        - queue msg count check:
            id: 1
            expected value: 5
            name: validation Mq check