configurations:
    databases:
        db1: jdbc:mysql://t-l-mysql01.ocnet.local:3306/oxalis?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result
tests:
   validation:
     producers:
       web ui producer:
         source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-xml-test
         destination link: http://localhost:441/
         result directory: validation result folder
       mq producer:
         mq connection: mq1
         source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-xml-test
         destination queue: validation-integration-test
       rest producer:
         source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-xml-test
         destination link: http://localhost:441/validate
         result directory: validation result folder
         rest method: post
     subscribers:
        - mq subscriber:
            mq connection: mq1
            source queue: validation-integration-test
            timeout: 500
            consumers: 1
        - snc subscriber:
            consumers: 2
            timeout: 500
        - file subscriber:
            source file:  C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result\restResult
            consumers: 3
        - file subscriber:
            source file:  C:\Peppol\peppol2.0\integration-tests\src\main\resources\validation-result\webUiResult
            consumers: 2
     consumers:
        - queue msg count check:
            id: 1
            expected value: 500
        - web ui check:
            id: 2
            expected value: 5
        - rest check:
            id: 3
            expected value: 5
   events-persistence:
     producers:
       mq producer:
         mq connection: mq1
         destination queue: events-persistence-integration-test
         source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\events-persistence-test
         db connection: db1
         DB preprocess querry: delete from messages where invoice_number='60445647'; delete from access_points where ap_id='123456' and ap_name='TEST'
     subscribers:
       - mq subscriber:
          mq connection: mq1
          source-queue: events-persistence-integration-test
          timeout: 500
       - snc subscriber:
          source directory: C:/var/lib/peppol2.0/events-persistence/error
          consumers: 7 8
          timeout: 500
       - snc subscriber:
           source directory: C:/var/lib/peppol2.0/events-persistence/invalid
           consumers: 9 10
           timeout: 500
       - db subscriber:
           db connection: db1
           query: select count(*) from messages where invoice_number="60445647"
           consumers: 4
       - db subscriber:
           db connection: db1
           query: select count(*) from access_points where ap_id="123456" and ap_name="TEST"
           consumers: 5
     consumers:
       - DB test:
          id: 4
          name: Message "status" can be seen in DB- positive test
          connection string: db1
          expected value: 1
       - DB test:
          id: 5
          name: New access point -> new entry in DB- positive
          connection string: db1
          expected value: 1
       - SNC test:
          name: Invalid message error case- ticket is sent to SNC (snc stub)
          id: 7
          expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8.xml
       - SNC test:
          name: Not JSON file in input- Error case -> ticket to SNC
          id: 8
          expected value: nojson
       - SNC test:
          name: Invalid msg field lenghts and corrupted contents- negative test
          id: 9
          expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8.xml
       - SNC test:
          name: correlationID start with invoice file name for SNC tickets- positive test
          id: 10
          expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8
   support-ui:
      producers:
        file producer:
          source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\support-ui-test
          destination directory: C:\peppol-ap-testout\failed
        db producer:
           db connection: db1
           source query:
      subscribers:
          - file subscriber:
              timeout: 500
              source file: C:\peppol-ap-testout\failed
      consumers:
         - selenium check:
            id: 11
            expected value: 500
   inbound:
     producers:
       file producer:
         source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\inbound-test
         destination directory: C:\tmp\
         commandline: docker exec -it inbound ./send-to-peppol.sh -f /tmp/*svefaktura_removed_sensetive_info.xml
     subscribers:
        - file subscriber:
            timeout: 500
            source file: C:\peppol-ap-testout\failed
        - snc subscriber:
            source directory: C:\test
            timeout: 500
     consumers:
      - snc test:
          id: 12
          name: Invalid message error case- ticket is sent to SNC (snc stub)
          expected value: invalid_svefaktura.xml
      - file test:
          id: 13
          name: Look for inbound files in long term storage
          dir: /var/lib/docker/volumes/peppol2.0/data/storage
          expected value: valid_svefaktura_removed_sensetive_info.xml