configurations:
    databases:
        db1: jdbc:mysql://mysql.docker.local:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: /etc/resources/validation-result
tests:
   events-persistence:
        producers:
          mq producer:
            mq connection: mq1
            destination queue: eventing
            source directory: /etc/resources/events-persistence-test
            db connection: db1
            endpoint: events-persistence-integration-test
            DB preprocess querry: delete from messages where invoice_number='60445647'; delete from access_points where ap_id='123456' and ap_name='TEST'
        subscribers:
          - mq subscriber:
             source-queue: events-persistence-integration-test
             timeout: 1500
          - snc subscriber:
             source directory: C:/var/lib/peppol2.0/events-persistence/error
             consumers: 7 8
             timeout: 1500
          - snc subscriber:
              source directory: C:/var/lib/peppol2.0/events-persistence/invalid
              consumers: 9 10
              timeout: 1500
          - db subscriber:
              db connection: db1
              query: select count(*) from messages where invoice_number="60445647"
              consumers: 4
          - db subscriber:
              db connection: db1
              query: select count(*) from access_points where ap_id="123456" and ap_name="TEST"
              consumers: 5
        consumers:
          - DB test:
             id: 4
             name: Message "status" can be seen in DB- positive test
             connection string: db1
             expected value: 1
          - DB test:
             id: 5
             name: New access point -> new entry in DB- positive
             connection string: db1
             expected value: 1
          - SNC test:
             name: Invalid message error case- ticket is sent to SNC (snc stub)
             id: 7
             expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8.xml
          - SNC test:
             name: Not JSON file in input- Error case -> ticket to SNC
             id: 8
             expected value: nojson
          - SNC test:
             name: Invalid msg field lenghts and corrupted contents- negative test
             id: 9
             expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8.xml
          - SNC test:
             name: correlationID start with invoice file name for SNC tickets- positive test
             id: 10
             expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8
tests:
   support-ui:
         producers:
           file producer:
             source directory: /etc/resources/support-ui-test/d78a50b0-eafa-41e2-b5ed-3f74989b1ced.xml
             destination directory: /peppol/data/storage/support-ui-test.xml
         subscribers:
            - file subscriber:
               consumers: 11
               timeout: 500
               source file: /peppol/data/storage/support-ui-test.xml
         consumers:
            - file download test:
               id: 11
               name: support ui download test
               action: download
               link: http://support-ui:8080/rest/outbound/download/
               expected value: true