#complete configuration for stage
configurations:
    databases:
        db1: jdbc:mysql://mysql:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: rabbitmq
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: /etc/resources/validation-result
tests:
   events-persistence:
        producers:
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/events-persistence_valid.xml
                db connection: db1
                DB preprocess querry: delete from messages where invoice_number='20828'
                container message:
                  endpoint: events-persistence-integration-test
        subscribers:
            - db subscriber:
                db connection: db1
                timeout: 10000
                query: select count(*) from messages where invoice_number="20828"
                consumers: 4
        consumers:
            - DB test:
                id: 4
                name: Message persisted into DB positive test
                expected value: 1
   eventing:
        producers:
            - file producer:
                source directory: /etc/resources/events-persistence-test/eventing-valid-mlr-backup.xml
                destination directory: /peppol/data/storage/eventing-valid-mlr-backup.xml
            - file producer:
                source directory: /etc/resources/mlr-reporter/mlr-reporter_valid_reprocess.xml
                destination directory: /peppol/data/storage/mlr-reporter_valid_reprocess.xml
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /peppol/data/storage/eventing-valid-mlr-backup.xml
                db connection: db1
                DB preprocess querry: delete from messages where invoice_number='12345678'
                container message:
                  endpoint: integration-test-endpoint
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/eventing_valid.xml
                db connection: db1
                DB preprocess querry: delete from messages where invoice_number='20830'
                container message:
                  source endpoint: integration-test-a2a
                  endpoint: integration-test-endpoint
                  endpoint type: outbound
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/eventing_rejected.xml
                db connection: db1
                DB preprocess querry: delete from messages where invoice_number='61016660'
                container message:
                  source endpoint: integration-test-xib
                  endpoint: integration-test-endpoint
                  endpoint type: outbound
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/eventing_invalid.xml
                container message:
                  source endpoint: integration-test-xib
                  endpoint type: outbound
                  endpoint: integration-test-endpoint
                  processing exception: This sending expected to fail I/O in test mode
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/events-persistence-test/eventing_invalid-snc-test.xml
                container message:
                  source endpoint: integration-test-xib
                  endpoint type: outbound
                  endpoint: integration-test-endpoint
            - mq producer:
                mq connection: mq1
                destination queue: eventing
                source directory: /etc/resources/mlr-reporter/mlr-reporter_valid_reprocess.xml
                container message:
                  source endpoint: integration-test-a2a
                  endpoint type: outbound
                  source type: outbound reprocess
                  endpoint: integration-test-endpoint
        subscribers:
            - directory subscriber:
                source directory: /peppol/data/snc-stub
                consumers: 5
            - directory subscriber:
                consumers: 6, 21
                source directory: /peppol/data/mlr-reporter/a2a/mlr
            - directory subscriber:
                consumers: 7 9
                source directory: /peppol/data/mlr-reporter/xib/mlr
        consumers:
            - file test:
                name: MLR a2a accepted creation test
                id: 6
                expected value: eventing_valid-ap-mlr.xml
                timeout: 16000
            - file test:
                name: MLR xib rejected creation test
                id: 7
                expected value: eventing_rejected-re-mlr.xml
                timeout: 16000
            - file test:
                name: MLR reprocessing test
                id: 21
                expected value: mlr-reporter_valid_reprocess-ap-mlr.xml
                timeout: 16000
            - mlr test:
                name: IO exception in mlr test
                id: 9
                expected value: '<cbc:Description>OTHER_ERROR: This sending expected to fail I/O in test mode</cbc:Description>'
                expected file: eventing_invalid-er-mlr.xml
                timeout: 16000
            - snc test:
                name: SNC ticket creation test
                id: 5
                expected value: 9908:937270067
                timeout: 16000
   support-ui:
        producers:
            - file producer:
                source directory: /etc/resources/support-ui-test/support-ui.xml
                destination directory: /peppol/data/storage/support-ui-test.xml
        subscribers:
            - file subscriber:
                consumers: 11
                timeout: 500
                source file: /peppol/data/storage/support-ui-test.xml
        consumers:
            - file download test:
                id: 11
                name: support ui download test
                action: download
                link: http://support-ui:8080/rest/outbound/download/
                expected value: true
   validation:
        producers:
            - file producer:
                source directory: /etc/resources/validation-xml-test
                destination directory: /peppol/data/storage/integration-test
            - mq producer:
                mq connection: mq1
                source directory: /peppol/data/storage/integration-test
                destination queue: validator
                container message:
                  endpoint: validation-integration-test
            - web ui producer:
                source directory: /etc/resources/validation-xml-test
                destination link: http://validator:8080/validator/
                result directory: validation result folder
            - rest producer:
                source directory: /etc/resources/validation-xml-test
                destination link: http://validator:8080/validator/validate
                result directory: validation result folder
                rest method: post
        subscribers:
            - mq subscriber:
                source queue: validation-integration-test
                timeout: 1500
                consumers: 1
            - file subscriber:
                source file:  /etc/resources/validation-result/restResult
                consumers: 3
            - file subscriber:
                source file:  /etc/resources/validation-result/webUiResult
                consumers: 2
        consumers:
            - queue msg count check:
                id: 1
                expected value: 4
                name: validation Mq check
            - web ui check:
                id: 2
                expected value: 4
                name: validation web ui check
            - rest check:
                id: 3
                expected value: 4
                name: validation rest check
   inbound:
        producers:
            - command producer:
                command: ./send-to-peppol.sh -f /etc/resources/inbound-test/inbound_valid_test_ehf.xml -u http://inbound:8080/peppol-ap-inbound/as2 -c /etc/resources/inbound-test/oxalis.cer
                preprocessing cleanup dir: /peppol/data/tmp/
        subscribers:
            - mq subscriber:
                source queue: preprocessing-integration-test
                timeout: 3000
                consumers: 12
            - directory subscriber:
                consumers: 15
                source directory: /peppol/data/tmp/
        consumers:
            - queue msg count check:
                id: 12
                expected value: 1
                name: inbound Mq check
            - inbound message check:
                id: 15
                expected value: 1
                name: inbound stored files check
                timeout: 18000
   internal-routing:
        producers:
            - mq producer:
                mq connection: mq1
                destination queue: internal-routing
                source directory: /etc/resources/internal-routing/internal-routing_valid_bis.xml
                container message:
                  source endpoint: peppol-integration
                  endpoint: integration-test-endpoint
                  endpoint type: inbound
        subscribers:
            - mq subscriber:
                source queue: transport-to-xib
                timeout: 1500
                consumers: 13
        consumers:
            - queue msg count check:
                id: 13
                expected value: 1
                name: internal-routing Mq check
#   outbound:
#        producers:
#            - file producer:
#                source directory: /etc/resources/outbound/outbound-integration-test-valid.xml
#                destination directory: /peppol/data/storage/outbound-integration-test-valid.xml
#            - mq producer:
#                mq connection: mq1
#                destination queue: outbound
#                source directory: /peppol/data/storage/outbound-integration-test-valid.xml
#                db connection: db1
#                DB preprocess querry: delete from sent where transmission_id = "OUToutbound-integration-test-valid.xml"
#                container message:
#                  endpoint: events-persistence-integration-test
#        subscribers:
#            - db subscriber:
#                db connection: db1
#                timeout: 5000
#                query: select count(*) from sent where transmission_id = "OUToutbound-integration-test-valid.xml"
#                consumers: 14
#        consumers:
#            - DB test:
#                id: 14
#                name: Outbound transmission id persisted into DB positive test
#                expected value: 1
   preprocessing:
        producers:
            - file producer:
                source directory: /etc/resources/preprocessing/preprocessing_invalid.xml
                destination directory: /peppol/data/tmp/preprocessing_invalid.xml
            - file producer:
                source directory: /etc/resources/preprocessing/preprocessing_valid.xml
                destination directory: /peppol/data/tmp/preprocessing_valid.xml
            - file producer:
                source directory: /etc/resources/preprocessing/preprocessing_unrecognized.xml
                destination directory: /peppol/data/tmp/preprocessing_unrecognized.xml
            - mq producer:
                mq connection: mq1
                destination queue: preprocessing
                source directory: /peppol/data/tmp/preprocessing_invalid.xml
                container message:
                  source endpoint: integration-test-a2a
                  endpoint: integration-test-endpoint
                  load file: 'false'
            - mq producer:
                mq connection: mq1
                destination queue: preprocessing
                source directory: /peppol/data/tmp/preprocessing_unrecognized.xml
                container message:
                  source endpoint: integration-test-a2a
                  endpoint: integration-test-endpoint
                  load file: 'false'
            - mq producer:
                mq connection: mq1
                destination queue: preprocessing
                source directory: /peppol/data/tmp/preprocessing_valid.xml
                container message:
                  source endpoint: integration-test-a2a
                  endpoint: integration-test-endpoint
                  endpoint type: outbound
        subscribers:
            - mq subscriber:
                source queue: preprocessing-error
                timeout: 2000
                consumers: 16
            - mq subscriber:
                source queue: preprocessing-out
                timeout: 2000
                consumers: 17
            - directory subscriber:
                consumers: 18 19
                source directory: /peppol/data/storage/0037_01098230/9908_939214895/
            - directory subscriber:
                source directory: /peppol/data/snc-stub
                consumers: 20
        consumers:
            - queue msg count check:
                id: 16
                expected value: 1
                name: preprocessing error queue check
            - queue msg count check:
                id: 17
                expected value: 1
                name: preprocessing out queue check
            - preprocessing check:
                id: 18
                expected value: '$date/preprocessing_valid.xml'
                name: preprocessing valid file check
            - preprocessing check:
                id: 19
                expected value: '$date/preprocessing_invalid.xml'
                name: preprocessing invalid file check
            - snc test:
                name: preprocessing SNC ticket creation test
                id: 20
                expected value: n_a_
                timeout: 16000