configurations:
    databases:
        db1: jdbc:mysql://t-l-mysql01.ocnet.local:3306/oxalis?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: rabbitmq
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: /etc/resources/validation-result
tests:
   validation:
     producers:
       mq producer:
         mq connection: mq1
         source directory: /etc/resources/validation-xml-test
         destination queue: validation
         endpoint: validation-integration-test
     subscribers:
        - mq subscriber:
            mq connection: mq1
            source queue: validation-integration-test
            timeout: 500
            consumers: 1
        - snc subscriber:
            consumers: 2
            timeout: 500
        - file subscriber:
            source file:  /etc/resources/validation-result/restResult
            consumers: 3
        - file subscriber:
            source file:  /etc/resources/validation-result/webUiResult
            consumers: 2
     consumers:
        - queue msg count check:
            id: 1
            expected value: 5
        - web ui check:
            id: 2
            expected value: 5
        - rest check:
            id: 3
            expected value: 5
   support-ui:
      producers:
        file producer:
          source directory: /etc/resources/support-ui-test/d78a50b0-eafa-41e2-b5ed-3f74989b1ced.xml
          destination directory: /etc/support-ui-test.xml
      subscribers:
          - file subscriber:
              consumers: 11
              timeout: 500
              source file: /etc/support-ui-test.xml
      consumers:
         - file download test:
            id: 11
            name: support ui download test
            action: download
            link: http://support-ui:8080/rest/outbound/download/
            expected value: true