tests:
   validation:
     producers:
       file producer:
         source file: source.xml
         destination file: input.xml
       mq producer:
         source file: source.json
         destination queue: queue name
       rest producer:
         source file: source.xml
         rest template file: file
         rest endpoint: value
         rest method: get/post
     subscribers:
        mq subscriber:
          timeout: 500
        snc subscriber:
          timeout: 500
     consumers:
        queue msg count check:
          subscribers:
           - mq subscriber
           - snc subscriber
          expected value: 500
   events-persistence:
     producers:
       mq producer:
         source file: source.json
         destination queue: queue name
     subscribers:
       mq subscriber:
         timeout: 500
       snc subscriber:
         timeout: 500
     consumers:
       DB query:
         expected value: 500
   support-ui:
      producers:
        file producer:
          source file: source.xml
          destination file: input.xml
        db producer:
           source query: query
      subscribers:
        db subscriber:
          timeout: 500
      consumers:
         selenium check:
           expected value: 500