configurations:
    databases:
        db1: jdbc:mysql://10.117.83.136:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: localhost
            port: 441
            username: guest
            password: guest
            virtual host: /
    validation result folder: etc/resources/validation-result
tests:
   eventing:
           producers:
               - mq producer:
                   mq connection: mq1
                   destination queue: eventing
                   source: integration-test-a2a
                   source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\events-persistence-test\ehf.xml
                   db connection: db1
                   endpoint: events-persistence-integration-test
                   endpoint type: outbound
                   DB preprocess querry: delete from messages where invoice_number='20828'
               - mq producer:
                   mq connection: mq1
                   destination queue: eventing
                   source directory: C:\Peppol\peppol2.0\integration-tests\src\main\resources\events-persistence-test\invalid.xml
                   endpoint: events-persistence-integration-test
           subscribers:
               - snc subscriber:
                   source directory: /peppol/data/snc-stub
                   consumers: 5
                   timeout: 1500
           consumers:
               - SNC test:
                   name: Invalida container message test
                   id: 5
                   expected value: 7ecd16db-bfc1-4374-9be7-3ec00a56e9f8.xml