configurations:
    databases:
        db1: jdbc:mysql://mysql.docker.local:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: etc/resources/validation-result
tests:
   support-ui:
         producers:
           file producer:
             source directory: etc/resources/support-ui-test/d78a50b0-eafa-41e2-b5ed-3f74989b1ced.xml
             destination directory: peppol/data/storage/support-ui-test.xml
         subscribers:
            - file subscriber:
               consumers: 11
               timeout: 500
               source file: peppol/data/storage/support-ui-test.xml
         consumers:
            - file download test:
               id: 11
               name: support ui download test
               action: download
               link: http://localhost:8080/rest/outbound/download/
               expected value: true