configurations:
    databases:
        db1: jdbc:mysql://mysql.docker.local:3306/peppol?user=oxalis&password=grAm0f0n_1982-X_&allowMultiQueries=true
    queues:
        mq1:
            host: rabbitmq
            port: 5672
            username: guest
            password: guest
            virtual host: /
    validation result folder: etc/resources/validation-result
tests:
      outbound:
           producers:
               - mq producer:
                   mq connection: mq1
                   destination queue: outbound
                   source directory: /etc/resources/outbound/
                   db connection: db1
                   endpoint: events-persistence-integration-test
                   DB preprocess querry: delete from messages where invoice_number='20828'
           subscribers:
               - mq subscriber:
                   source queue: preprocessing-integration-test
                   timeout: 1500
                   consumers: 12
           consumers:
               - queue msg count check:
                   id: 12
                   expected value: 1
                   name: inbound Mq check