---
#File_list.yml#
#This is where all the test materials are taken from #

#send to outbound flow
- include: file_to_transport-from-a2a.yml
  vars:
    file: "{{item}}"
  with_fileglob:
    - "{{test_data_path}}/performance-tests-materials/performance-test-100/*"

#send to inbound flow
- include: file_to_inbound.yml
  vars:
    file: "{{item}}"
  with_fileglob:
    - "{{test_data_path}}/performance-tests-materials/performance-test-10/*"
...

