---
#                                         s/.            ./s
#                                          y.+/.        ./+.y
#                                ./.-.     y  .+/.    ./+.  y      +./-
#                                .:sy:     y    .//  //.    y     .hy+.
#                                 .../+.+  y      s..s      y  +-/+.
#                                    ./sy. s.     s..s     .y .os+-
#                                       ./+-//.   s..s   .+/.//.
#                           .+y/::::::::+:.:+-/+. s..s .+/.//.:+::::::::/y+.
#                             .+/.       .+:.:+-/+y..y+/.//.:+.       ./+.
#                               .+/.       .+:.:+-/.././/.:+.       ./+.
#                                 .+/::::::::+y:.:ooo+/.:y+:::::::://.
#                                   ............ :hhhh: ............
#                                 .+/-------:+s:.+/++:+-:s+--------/+.
#                               .+:        -+:.+/./../.:+-:+-        :+.
#                             .+:        -+:.+/.//y..y//.:+-:+-        :+.
#                           .+s/::::::::+-.+/.//. s..s .//.-+-:+::::::::/s+.
#                                     ..-+:.//.   s..s   .//.-+-...
#                                     :sy. y.     s..s     .y  ss+-
#                                 -::+: :. y      s..s      y  :.-+:--.
#                                 -+o/     y    .+:  :+.    y     .yo/.
#                                .: ..     y  .+:      :+.  y      - -.
#                                          y-+:          :+-y
#                                          s:              :s

#Author: Martins Berzins
#Date: 2018

#- name: Clean storage/performance-tests/tmp
#  become: true
#  file:
#    state: absent
#    path: "{{ item }}"
#  with_items:
#    - /peppol/data/storage/performance-tests/tmp

#define stuff
#- include: rabbitmqadmin.yml
- set_fact: file="/peppol/data/storage/performance-tests/small-file/small-file-16KB.xml"

# generate uuid with shell for FIRST file
- set_fact: uuidf="{{99999 | random | to_uuid}}"
- name: debug uuidf
  debug: var=uuidf

- name: Copy file to storage/performance-tests
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "/peppol/data/storage/performance-tests/tmp/{{ file| basename }}-{{ uuidf }}.xml"
- name: debug filename
  debug: var=file

- set_fact: first_filename="/peppol/data/storage/performance-tests/tmp/{{ file| basename  }}-{{ uuidf }}.xml"
- name: debug first_filename
  debug: var=first_filename

# generate uuid with shell for LAST file
- set_fact: uuidl="{{99999 | random | to_uuid}}"
- name: debug uuidl
  debug: var=uuidl

- name: Copy file to storage/performance-tests
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "/peppol/data/storage/performance-tests/tmp/{{ file| basename }}-{{ uuidl }}.xml"
- name: debug LAST filename
  debug: var=file

- set_fact: last_filename="/peppol/data/storage/performance-tests/tmp/{{ file| basename  }}-{{ uuidl }}.xml"
- name: debug last_filename
  debug: var=last_filename

- name: stop validator
  shell: docker stop validator

#send FIRST msg:
- name: send FIRST msg to MQ
  shell: rabbitmqadmin publish exchange=peppol routing_key=validator payload='{"version":1.1,"processingInfo":{"source":{"name":"transport-from-a2a","type":"OUT_FILE_TO_MQ"},"sourceMetadata":"Received by transport-from-a2a as /peppol-a2a-nfs/out/test/data/small-file-16KB.xml","route":{"endpoints":["validator","outbound","outbound:exchange=peppol-delayed,x-delay=30000","outbound:exchange=peppol-delayed,x-delay=30000"],"description":"A2A to Peppol","source":"transport-from-a2a","current":1},"currentEndpoint":{"name":"internal-routing","type":"OUT_ROUTING"},"currentStatus":"route set","attemptId":0,"eventingMessage":{"id":"OUT_small-file-16KB_transport-from-a2a","created":1518104253865,"isInbound":false,"attempts":[{"id":"1518104253868_small-file-16KB.xml","events":[{"id":1518104253869,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104253871,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104255384,"source":"preprocessing","status":"parsed","terminal":false,"details":"Preprocessing complete, sent to internal-routing"},{"id":1518104255387,"source":"internal-routing","status":"route set","terminal":false,"details":"Route set, sent to validator"}],"filename":"/peppol/data/storage/9908_987987987/9908_987987987/20180208/small-file-16KB.xml"}],"documentType":"Invoice","documentNumber":"92426725","documentDate":"2016-06-30","dueDate":"2016-07-15"}},"fileName":"{{ first_filename }}","originalFileName":"small-file-16KB","documentInfo":{"errors":[],"warnings":[],"senderId":"9908:987987987","recipientId":"9908:987987987","versionId":"2.1","documentId":"92426725","issueDate":"2016-06-30","issueTime":"","dueDate":"2016-07-15","senderName":"OpusCapita test","senderCountryCode":"NO","recipientName":"OpusCapita test","recipientCountryCode":"NO","profileId":"urn:www.cenbii.eu:profile:bii05:ver2.0","customizationId":"urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0","rootNameSpace":"urn:oasis:names:specification:ubl:schema:xsd:Invoice-2","rootNodeName":"Invoice","archetype":"EHF","documentType":"Invoice","documentBusinessIdentifier":"ff3bb2dc-3ff4-11e6-9605-97ed9690fe22"}}'

#send 98 other msg:

- name: send msg to MQ
  shell: rabbitmqadmin publish exchange=peppol routing_key=validator payload='{"version":1.1,"processingInfo":{"source":{"name":"transport-from-a2a","type":"OUT_FILE_TO_MQ"},"sourceMetadata":"Received by transport-from-a2a as /peppol-a2a-nfs/out/test/data/small-file-16KB.xml","route":{"endpoints":["validator","outbound","outbound:exchange=peppol-delayed,x-delay=30000","outbound:exchange=peppol-delayed,x-delay=30000"],"description":"A2A to Peppol","source":"transport-from-a2a","current":1},"currentEndpoint":{"name":"internal-routing","type":"OUT_ROUTING"},"currentStatus":"route set","attemptId":0,"eventingMessage":{"id":"OUT_small-file-16KB_transport-from-a2a","created":1518104253865,"isInbound":false,"attempts":[{"id":"1518104253868_small-file-16KB.xml","events":[{"id":1518104253869,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104253871,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104255384,"source":"preprocessing","status":"parsed","terminal":false,"details":"Preprocessing complete, sent to internal-routing"},{"id":1518104255387,"source":"internal-routing","status":"route set","terminal":false,"details":"Route set, sent to validator"}],"filename":"/peppol/data/storage/9908_987987987/9908_987987987/20180208/small-file-16KB.xml"}],"documentType":"Invoice","documentNumber":"92426725","documentDate":"2016-06-30","dueDate":"2016-07-15"}},"fileName":"/peppol/data/storage/performance-tests/small-file/small-file-16KB.xml","originalFileName":"small-file-16KB","documentInfo":{"errors":[],"warnings":[],"senderId":"9908:987987987","recipientId":"9908:987987987","versionId":"2.1","documentId":"92426725","issueDate":"2016-06-30","issueTime":"","dueDate":"2016-07-15","senderName":"OpusCapita test","senderCountryCode":"NO","recipientName":"OpusCapita test","recipientCountryCode":"NO","profileId":"urn:www.cenbii.eu:profile:bii05:ver2.0","customizationId":"urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0","rootNameSpace":"urn:oasis:names:specification:ubl:schema:xsd:Invoice-2","rootNodeName":"Invoice","archetype":"EHF","documentType":"Invoice","documentBusinessIdentifier":"ff3bb2dc-3ff4-11e6-9605-97ed9690fe22"}}'
  with_sequence: count=3

#- name: generate uuid with shell
- set_fact: uuidl="{{99999 | random | to_uuid}}"
- name: debug uuidl
  debug: var=uuidl

- name: Copy file to storage/performance-tests
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: "{{file}}"
    dest: "/peppol/data/storage/performance-tests/tmp/{{ file| basename }}-{{ uuidl }}.xml"
- name: debug LAST filename
  debug: var=file

- set_fact: last_filename="/peppol/data/storage/performance-tests/tmp/{{ file| basename  }}-{{ uuidl }}.xml"
- name: debug last_filename
  debug: var=last_filename


#send LAST msg:
- name: send LAST msg to MQ
  shell: rabbitmqadmin publish exchange=peppol routing_key=validator payload='{"version":1.1,"processingInfo":{"source":{"name":"transport-from-a2a","type":"OUT_FILE_TO_MQ"},"sourceMetadata":"Received by transport-from-a2a as /peppol-a2a-nfs/out/test/data/small-file-16KB.xml","route":{"endpoints":["validator","outbound","outbound:exchange=peppol-delayed,x-delay=30000","outbound:exchange=peppol-delayed,x-delay=30000"],"description":"A2A to Peppol","source":"transport-from-a2a","current":1},"currentEndpoint":{"name":"internal-routing","type":"OUT_ROUTING"},"currentStatus":"route set","attemptId":0,"eventingMessage":{"id":"OUT_small-file-16KB_transport-from-a2a","created":1518104253865,"isInbound":false,"attempts":[{"id":"1518104253868_small-file-16KB.xml","events":[{"id":1518104253869,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104253871,"source":"transport-from-a2a","status":"received","terminal":false,"details":"Picked up file by transport"},{"id":1518104255384,"source":"preprocessing","status":"parsed","terminal":false,"details":"Preprocessing complete, sent to internal-routing"},{"id":1518104255387,"source":"internal-routing","status":"route set","terminal":false,"details":"Route set, sent to validator"}],"filename":"/peppol/data/storage/9908_987987987/9908_987987987/20180208/small-file-16KB.xml"}],"documentType":"Invoice","documentNumber":"92426725","documentDate":"2016-06-30","dueDate":"2016-07-15"}},"fileName":"{{ last_filename }}","originalFileName":"small-file-16KB","documentInfo":{"errors":[],"warnings":[],"senderId":"9908:987987987","recipientId":"9908:987987987","versionId":"2.1","documentId":"92426725","issueDate":"2016-06-30","issueTime":"","dueDate":"2016-07-15","senderName":"OpusCapita test","senderCountryCode":"NO","recipientName":"OpusCapita test","recipientCountryCode":"NO","profileId":"urn:www.cenbii.eu:profile:bii05:ver2.0","customizationId":"urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0","rootNameSpace":"urn:oasis:names:specification:ubl:schema:xsd:Invoice-2","rootNodeName":"Invoice","archetype":"EHF","documentType":"Invoice","documentBusinessIdentifier":"ff3bb2dc-3ff4-11e6-9605-97ed9690fe22"}}'

- name: start validator
  shell: docker start validator

#- name: Read in FIRST processing timestamp
- name: get validator log & check if "{{ uuidf }}" is found in validator
  ignore_errors: yes
  shell: docker logs validator | grep "Processing message.*{{ uuidf }}"
  register: logf
  until: 'uuidf in logf.stdout'
  retries: 300
  delay: 1
- name: debug FIRST grep
  debug: var=logf.stdout
- name: get timestamp
  shell: echo "{{ logf.stdout }}" | awk '{sub(/INFO.*/,x)}1'
  register: first_timestamp
- name: debug FIRST timestamp
  debug: var=first_timestamp
- set_fact: first_timestamp="{{ first_timestamp }}"
- name: debug FIRST timestamp
  debug: var=first_timestamp
 

#- name: Read in LAST processing timestamp
- name: get validator log & check if  is found in validator
  ignore_errors: yes
  shell: docker logs validator | grep "Validation failed for.*{{ uuidl }}"
  register: logl
  until: 'uuidl in logl.stdout'
  retries: 300
  delay: 1
- name: debug FIRST grep
  debug: var=logl.stdout

...
