routing:
  routes:
    - description: 'Peppol to XiB'
      mask: '007:.*'
      source: peppol
      endpoints:
        - validation
        - gateway_xib

    - description: 'Peppol to A2A'
      mask: '.*'
      source: peppol
      endpoints:
        - validation
        - gateway_a2a

    - description: 'A2A to Peppol'
      source: gateway_a2a
      endpoints:
        - validation
        - peppol

    - description: 'XiB to Peppol'
      source: gateway_xib
      endpoints:
        - validation
        - peppol
