---
- set_fact: file=/test-materials/EHF/EHF_2.0.12/catalogue/validid_ehf_catalogue.xml
- set_fact: expected="'OP-T19-R014'"
- set_fact: expected1="'OP-T19-R015'"
- set_fact: valid="true"
- set_fact: active="true"

- include: send_to_REST.yml
- include: response_set.yml

- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"
  when: result_validationError!=''
- debug: var=result_identifier

- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"
- set_fact: result_identifier1="{{ result_warnings.1.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} or {{ expected1 }} "
      - "result_identifier1 == {{ expected }} or {{ expected1 }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/catalogue/NOGOV-T19-R024.xml
- set_fact: expected="'NOGOV-T19-R024'"
- set_fact: expected1="'OP-T19-R014'"
- set_fact: expected2="'OP-T19-R015'"
- set_fact: valid="false"
- set_fact: active="true"

- include: send_to_REST.yml
- include: response_set.yml

- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"
  when: result_validationError!=''
- set_fact: result_identifier1="{{ result_warnings.0.validationError.identifier }}"
  when: result_validationError!=''
- set_fact: result_identifier2="{{ result_warnings.1.validationError.identifier }}"
  when: result_validationError!=''

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} or {{ expected1 }} or {{ expected2 }} "
      - "result_identifier1 == {{ expected }} or {{ expected1 }} or {{ expected2 }} "
      - "result_identifier2 == {{ expected }} or {{ expected1 }} or {{ expected2 }} "
    msg: "Test for {{ file }} failed"
  when: active==true 
  register: assert_result

- include: reporter.yml
#-------------------------------

...
