---
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R001.xml
- set_fact: expected="'EHF-COMMON-R001'"
- set_fact: expected1="'EUGEN-T10-R047'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"
- set_fact: result_identifier1="{{ result_warnings.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
      - "result_identifier1 == {{ expected1 }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R002.xml
- set_fact: expected="'EHF-COMMON-R002'"
- set_fact: expected1="'EUGEN-T10-R047'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"
- set_fact: result_identifier1="{{ result_warnings.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
      - "result_identifier1 == {{ expected1 }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R003.xml
- set_fact: expected="'EHF-COMMON-R003'"
- set_fact: valid="true"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R004.xml
#- set_fact: expected="'EHF-COMMON-R004'"
#this error happens before validation, in document loader so custom check is needed
- set_fact: expected="Missing mandatory field{{":"}} version_id"
- set_fact: valid="false"
- set_fact: active="true"
- set_fact: notes="EHF-COMMON-R004- UBLVersionID must be present-  custom test as document loader checks for mandatory fields before validation"

- include: send_to_REST.yml
- include: response_set.yml

- set_fact: result_identifier="{{ result_errors.0.message }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_passed == {{ valid }}"
      - "expected in result_identifier"
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R010.xml
- set_fact: expected="'EHF-COMMON-R010'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R011.xml
- set_fact: expected="'EHF-COMMON-R011'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R012.xml
- set_fact: expected="'EHF-COMMON-R012'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R013.xml
- set_fact: expected="'EHF-COMMON-R013'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R014.xml
- set_fact: expected="'EHF-COMMON-R014'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R020.xml
- set_fact: expected="'EHF-COMMON-R020'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------

- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R020-invoice-valid.xml
- set_fact: valid="true"
- set_fact: active="true"
- set_fact: notes="Adding tax categories AE and G "

- include: send_to_REST.yml
- include: response_set.yml

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result
- debug: var=assert_result

- include: reporter.yml
#-------------------------------

- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R020-creditnote-valid.xml
- set_fact: valid="true"
- set_fact: active="true"
- set_fact: notes="Adding tax categories AE and G "

- include: send_to_REST.yml
- include: response_set.yml

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result
- debug: var=assert_result

- include: reporter.yml
#-------------------------------

- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R030.xml
- set_fact: expected="'EHF-COMMON-R030'"
- set_fact: valid="false"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R040.xml
- set_fact: expected="'EHF-COMMON-R040'"
- set_fact: valid="true"
- set_fact: active="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------
- set_fact: file=/test-materials/EHF/EHF_2.0.12/common/EHF-COMMON-R100.xml
- set_fact: expected="'EHF-COMMON-R100'"
- set_fact: valid="true"
- set_fact: active="true"

- include: send_to_REST.yml
- include: response_set.yml

- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"
  when: result_warnings.0 is defined

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  when: active==true
  register: assert_result

- include: reporter.yml
#-------------------------------

...
