---
- include: variable_cleaner.yml
#+++++++++++++++++++++++++++++++
#      EHF tests
#+++++++++++++++++++++++++++++++
- include: ehf-invoice.yml
- include: ehf-creditnote.yml
- include: ehf-catalogue.yml
#-------------------------------

#+++++++++++++++++++++++++++++++
#      peppol-bis tests
#+++++++++++++++++++++++++++++++
- include: peppol-bis-invoice.yml
#-------------------------------

#+++++++++++++++++++++++++++++++
#      Final report check
#+++++++++++++++++++++++++++++++
- include: report_checker.yml
...
