---
- set_fact: file=/test-materials/peppol-bis/invoice/OP-T10-R056-R057-T10-R0061-deprecatedUOM.xml
- set_fact: expected="'OP-T10-R056'"
- set_fact: expected1="'OP-T10-R057'"
- set_fact: valid="true"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- set_fact: result_identifier="{{ result_warnings.0.validationError.identifier }}"
- set_fact: result_identifier1="{{ result_warnings.1.validationError.identifier }}"

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_errors == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
      - "result_identifier1 == {{ expected1 }} "
    msg: "Test for {{ file }} failed"
  register: assert_result

- include: reporter.yml
#-------------------------------

- set_fact: file=/test-materials/peppol-bis/invoice/BII2-T10-R033-T10-R0060-commodity.xml
- set_fact: expected="'BII2-T10-R033'"
- set_fact: valid="false"

- name: send {{ file }} to validator REST
  shell: curl -F "file=@{{ file }}" localhost:8083/validator/validate
  register: result
- debug: var=result

- set_fact: result_errors="{{ (result.stdout | from_json).errors }}"
- debug: var=result_errors

- set_fact: result_warnings="{{ (result.stdout | from_json).warnings }}"
- debug: var=result_warnings

- set_fact: result_passed="{{ (result.stdout | from_json).passed }}"
- debug: var=result_passed

- set_fact: result_identifier="{{ result_errors.0.validationError.identifier }}"
- debug: var=result_identifier

- name: check if validation is correct for {{ file }}
  ignore_errors: yes
  assert:
    that:
      - "result_warnings == []"
      - "result_passed == {{ valid }}"
      - "result_identifier == {{ expected }} "
    msg: "Test for {{ file }} failed"
  register: assert_result
- debug: var=assert_result

- include: reporter.yml
#-------------------------------

...
