---
#This creates report about validation tests
- set_fact: counter="{{counter| int +1 }}"
  register: counter

- debug: var=counter

- name: update test results
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/validator-report-{{ansible_date_time.iso8601_basic}}.txt"
    state: present
    line: '{{ counter }},File: {{ file }}, Expected:{{ expected }} {{ expected1 }} 
    {{ expected2 }}{{ expected3 }} {{ expected4 }} {{ expected5 }} {{ expected6 }} , Result:{{ assert_result }}'

#kind of global variable reseter->
- include: variable_cleaner.yml
...
