---
#This creates report about validation tests
- set_fact: counter="{{counter| int +1 }}"
  register: counter

- debug: var=counter

- name: create report headers
  delegate_to: localhost
  lineinfile:
    create: yes
    dest: "{{report_path}}/validator-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: 'Test counter,Test file,Expected test results,Test result, Notes'

- name: update test results
  delegate_to: localhost
  lineinfile:
    create: no
    dest: "{{report_path}}/validator-report-{{ansible_date_time.iso8601_basic}}.csv"
    state: present
    line: '{{ counter }},{{ file }},{{ expected }} {{ expected1 }} 
    {{ expected2 }} {{ expected3 }} {{ expected4 }} {{ expected5 }} {{ expected6 }} ,{{ assert_result }}, {{ notes }}'

#kind of global variable reseter->
- include: variable_cleaner.yml
...
