---
#                                         s/.            ./s
#                                          y.+/.        ./+.y
#                                ./.-.     y  .+/.    ./+.  y      +./-
#                                .:sy:     y    .//  //.    y     .hy+.
#                                 .../+.+  y      s..s      y  +-/+.
#                                    ./sy. s.     s..s     .y .os+-
#                                       ./+-//.   s..s   .+/.//.
#                           .+y/::::::::+:.:+-/+. s..s .+/.//.:+::::::::/y+.
#                             .+/.       .+:.:+-/+y..y+/.//.:+.       ./+.
#                               .+/.       .+:.:+-/.././/.:+.       ./+.
#                                 .+/::::::::+y:.:ooo+/.:y+:::::::://.
#                                   ............ :hhhh: ............
#                                 .+/-------:+s:.+/++:+-:s+--------/+.
#                               .+:        -+:.+/./../.:+-:+-        :+.
#                             .+:        -+:.+/.//y..y//.:+-:+-        :+.
#                           .+s/::::::::+-.+/.//. s..s .//.-+-:+::::::::/s+.
#                                     ..-+:.//.   s..s   .//.-+-...
#                                     :sy. y.     s..s     .y  ss+-
#                                 -::+: :. y      s..s      y  :.-+:--.
#                                 -+o/     y    .+:  :+.    y     .yo/.
#                                .: ..     y  .+:      :+.  y      - -.
#                                          y-+:          :+-y
#                                          s:              :s

#Author: Martins Berzins
#Date: 2018

- name: copy Robot test to stage
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: /home/berzima1/git/peppol2.0/system-tests/robot-system-tests/test.robot
    dest: /tmp/test-bin/test.robot

- name: copy Robot test resources to stage
  become: "{{sudo}}"
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: /home/berzima1/git/peppol2.0/system-tests/robot-system-tests/resources/EHF_profile-bii05_invoice_OC.xml
    dest: /tmp/test-resources/EHF_profile-bii05_invoice_OC.xml

- name: Run Robot Framework test
  become: "{{sudo}}"
  become_user: "{{user}}"
  delegate_to: localhost
  shell: robot --NoStatusRC --output /tmp/test-reports/output.xml --log /tmp/test-reports/log.html --report /tmp/test-reports/report.html /tmp/test-bin/test.robot
  register: report

- name: debug report
  debug: var=report
...
